name: Release on version tag push
on:
  push:
    tags:
      - v[0-9]*
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu x86_64-unknown-linux-gnu
          override: true
          profile: minimal
      - name: Build for windows
        run: cargo build --release --target x86_64-pc-windows-gnu --out-dir release -Z unstable-options
      - name: Build for linux
        run: cargo build --release --target x86_64-pc-windows-gnu --out-dir release -Z unstable-options