name: Release on version tag push
on:
  push:
    tags:
      - v[0-9]*
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }} --out-dir release-dir -Z unstable-options
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: release-dir/*
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release
          path: release-dir/
      - uses: softprops/action-gh-release@v1
        with:
          files: release-dir/*
